export enum PaymentStatus {
    PROCESSING = "PROCESSING",
    PENDING  = "PENDING ",
    APPROVED = "APPROVED",
    REJECTED = "REJECTED",
    FAILED = "FAILED",
    NO_TRANSACTION_FOUND = "NO_TRANSACTION_FOUND"
}